create table genre
(
    genre_id bigint not null primary key,
    name     varchar(255)
);

create table author
(
    author_id bigint not null primary key,
    full_name varchar(255)
);

drop table if exists book cascade;
create table book
(
    id          bigint generated by default as identity primary key,
    url_image   varchar(255),
    author_id   bigint references author (author_id),
    genre_id    bigint references genre (genre_id),
    name        varchar(255),
    price       bigint,
    rating      double precision,
    total_views bigint
);