drop table if exists book cascade;
create table book (
    id int8 generated by default as identity,
    name varchar(255),
    price int8,
    rating float8,
    total_views int8,
    genre_id int8,
    author_id int8,
    primary key (id)
    );

drop table if exists genre cascade;
create table genre(
    genre_id int8,
    name varchar(255),
    primary key (genre_id)
);

drop table if exists author cascade;
create table author(
    author_id int8,
    full_name varchar(255),
    primary key (author_id)
);